This is the NLP class workshop-3 working with SMS-spam-collection-dataset. 

1. Use the previous dataset “spam dictation”
2.   Preprocess text including:
    
*  Remove white space
*  Remove anything that is not English
* Calculate word length and added with column name “length”


3. Create new column name “text2”
4. Use labelEncoder method to convert class target
5.  Use CountVectorize to perform BOW
6.  List Top 5 and bottom 5 of transform sample to show the resultsand submit your works to MS team

In [18]:
import nltk
import pandas as pd
import re

#load the dataset
df = pd.read_csv("Datasets/spam.csv",encoding='latin-1')
print("loaded dataset!")
df

loaded dataset!

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [19]:
# Drop the specified columns
df.drop(columns=["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], inplace=True)

# Display the updated DataFrame
print(df)

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [20]:
#remove whitespaces and convert to lowercase 
df['v2'] = df['v2'].apply(lambda x: x.lower())
df['v2'] = df['v2'].apply(lambda x: re.sub(r'\s+', ' ', x))
df['v2']

0       go until jurong point, crazy.. available only ...
1                           ok lar... joking wif u oni...
2       free entry in 2 a wkly comp to win fa cup fina...
3       u dun say so early hor... u c already then say...
4       nah i don't think he goes to usf, he lives aro...
                              ...
5567    this is the 2nd time we have tried 2 contact u...
5568                will ì_ b going to esplanade fr home?
5569    pity, * was in mood for that. so...any other s...
5570    the guy did some bitching but i acted like i'd...
5571                           rofl. its true to its name
Name: v2, Length: 5572, dtype: object

In [21]:
#remove anything that is not English
df['v2'] = df['v2'].apply(lambda x: re.sub(r'[^a-zA-Z]', ' ', x))
df['v2']

0       go until jurong point  crazy   available only ...
1                           ok lar    joking wif u oni
2       free entry in   a wkly comp to win fa cup fina...
3       u dun say so early hor    u c already then say
4       nah i don t think he goes to usf  he lives aro...
                              ...
5567    this is the  nd time we have tried   contact u...
5568                will    b going to esplanade fr home
5569    pity    was in mood for that  so   any other s...
5570    the guy did some bitching but i acted like i d...
5571                           rofl  its true to its name
Name: v2, Length: 5572, dtype: object

In [22]:
if 'v1' in df.columns and 'v2' in df.columns:
    df['label'] = df['v1']
    df['text'] = df['v2']
else:
    print("Column 'v1' and 'v2' does not exist in the DataFrame.")
    df.drop(columns=['v1', 'v2'], inplace=True)

df = df[['label', 'text']]
df['length'] = df['text'].apply(lambda x: len(x.split()))
    
df

/var/folders/tl/prng6d3x0sg5pgynysrs6g7c0000gn/T/ipykernel_76175/1674331322.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['length'] = df['text'].apply(lambda x: len(x.split()))

     label                                               text  length
0      ham  go until jurong point  crazy   available only ...      20
1      ham                      ok lar    joking wif u oni          6
2     spam  free entry in   a wkly comp to win fa cup fina...      30
3      ham  u dun say so early hor    u c already then say         11
4      ham  nah i don t think he goes to usf  he lives aro...      14
...    ...                                                ...     ...
5567  spam  this is the  nd time we have tried   contact u...      28
5568   ham              will    b going to esplanade fr home        7
5569   ham  pity    was in mood for that  so   any other s...      10
5570   ham  the guy did some bitching but i acted like i d...      27
5571   ham                         rofl  its true to its name       6

[5572 rows x 3 columns]

In [23]:

import nltk

# Ensure nltk resources are downloaded
nltk.download('words')
nltk.download('punkt')
words = set(nltk.corpus.words.words())


# Assuming `words` is a set of valid vocabulary words
# Example: words = set(["word1", "word2", "example", ...])
df['text2'] = df['text'].apply(
    lambda x: " ".join(
        w for w in nltk.wordpunct_tokenize(x) 
        if w.lower() in words or not w.isalpha()
    )
)

df

[nltk_data] Downloading package words to
[nltk_data]     /Users/ayenyeinsan/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/ayenyeinsan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,label,text,length,text2
0,ham,go until jurong point crazy available only ...,20,go until point crazy available only in n great...
1,ham,ok lar joking wif u oni,6,lar u
2,spam,free entry in a wkly comp to win fa cup fina...,30,free entry in a to win fa cup final st may tex...
3,ham,u dun say so early hor u c already then say,11,u dun say so early u c already then say
4,ham,nah i don t think he goes to usf he lives aro...,14,i don t think he goes to he around here though
...,...,...,...,...
5567,spam,this is the nd time we have tried contact u...,28,this is the time we have tried contact u u hav...
5568,ham,will b going to esplanade fr home,7,will b going to esplanade home
5569,ham,pity was in mood for that so any other s...,10,pity was in mood for that so any other
5570,ham,the guy did some bitching but i acted like i d...,27,the guy did some but i like i d be interested ...
5571,ham,rofl its true to its name,6,its true to its name

In [24]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

# Get the English stopwords
stop_words = set(stopwords.words('english'))

# Remove stopwords from the text
df['text2'] = df['text2'].apply(
    lambda x: " ".join(word for word in x.split() if word.lower() not in stop_words)
)

print(df['text2'].head())

0    go point crazy available n great world la e bu...
1                                                lar u
2    free entry win fa cup final st may text fa rec...
3                      u dun say early u c already say
4                             think goes around though
Name: text2, dtype: object

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/ayenyeinsan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [25]:
#labelEncoding the target variable 
!pip3 install scikit-learn
from sklearn.preprocessing import LabelEncoder
#label encoding the target variable(ham,spam) into numerical data

df['label_transform']= LabelEncoder().fit_transform(df['label'])
df['label_transform'].value_counts()
#0 is ham and 1 is spam

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.6.0)
Requirement already satisfied: numpy>=1.19.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (2.2.1)
Requirement already satisfied: scipy>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (3.5.0)

label_transform
0    4825
1     747
Name: count, dtype: int64

In [26]:
#count the count of unique words changing text data  to numerical data
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words=None,token_pattern=r'\b\w+\b')
matrix = vectorizer.fit_transform(df['text2'])

# Convert to array and inspect the result
print(matrix.toarray())  # This should now contain non-zero values
print("Total unique words:", len(vectorizer.get_feature_names_out()))  # Total unique words

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Total unique words: 3695

In [27]:
matrix_array = pd.DataFrame(matrix.toarray(),columns= vectorizer.get_feature_names_out())
matrix_array

,aa,abbey,abdomen,ability,able,abnormally,abroad,absence,absolutely,abstract,...,yor,young,younger,yr,yummy,z,zac,zebra,zed,zoom
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
#Sorting the top 10 words
import pandas as pd

# Calculate the sum for each feature (column)
word_sums = matrix_array.sum(axis=0)

# Sort the words by their total frequency in descending order
top_words = word_sums.sort_values(ascending=False).head(10)

print(top_words)

u       1212
call     606
get      397
ur       385
free     288
go       286
know     261
like     245
good     245
day      242
dtype: int64

In [29]:
#first 5 rows of the transformed dataset
print ("Top 5 rows of the transformed dataset")
matrix_array.head(5)

Top 5 rows of the transformed dataset

,aa,abbey,abdomen,ability,able,abnormally,abroad,absence,absolutely,abstract,...,yor,young,younger,yr,yummy,z,zac,zebra,zed,zoom
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
#Bottom 5 rows of the transformed dataset
print ("Bottom 5 rows of the transformed dataset")
matrix_array.tail(5)

Bottom 5 rows of the transformed dataset

,aa,abbey,abdomen,ability,able,abnormally,abroad,absence,absolutely,abstract,...,yor,young,younger,yr,yummy,z,zac,zebra,zed,zoom
5567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
#KDD (Knowledge Discovery in database ) process 
#split the BOW data into training and testing data

from sklearn.model_selection import train_test_split
X= matrix_array #features=bag of words matrix
Y= df['label_transform'] #target variable

# Split data into training (80%) and testing (20%)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (4457, 3695)
Testing data shape: (1115, 3695)

In [32]:
from sklearn.linear_model import LogisticRegression

# Train a logistic regression model
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)
y_predict = classifier.predict(X_test)

In [33]:
#measure the accuracy of the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, y_predict)
print("Model accuracy: {:.2f}%".format(accuracy * 100))

Model accuracy: 97.85%

Precision, Recall, and F1-Score: These metrics provide additional insights into the performance of your classifier.

Accuracy: Indicates how well the model performed overall.

Precision: Shows how many predicted spam messages were actually spam.

Recall: Reflects how many actual spam messages were correctly identified.

F1-Score: A harmonic mean of precision and recall, useful for imbalanced datasets.

In [34]:
from sklearn.metrics import classification_report

report = classification_report(Y_test, y_predict, target_names=['ham', 'spam'])
print("Classification Report:\n", report)

Classification Report:
               precision    recall  f1-score   support

         ham       0.98      1.00      0.99       965
        spam       1.00      0.84      0.91       150

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

In [35]:
df['text2']

0       go point crazy available n great world la e bu...
1                                                   lar u
2       free entry win fa cup final st may text fa rec...
3                         u dun say early u c already say
4                                think goes around though
                              ...
5567    time tried contact u u pound prize claim easy ...
5568                               b going esplanade home
5569                                            pity mood
5570    guy like interested something else next week g...
5571                                            true name
Name: text2, Length: 5572, dtype: object

### Using TF-IDF technique

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Use the same vectorizer instance
tfid_vectorizer = TfidfVectorizer(min_df=5)
X = tfid_vectorizer.fit_transform(df['text2'])  # TF-IDF sparse matrix
X_df = pd.DataFrame(X.toarray(), columns=tfid_vectorizer.get_feature_names_out())
X_df

,able,accept,access,account,across,activate,actually,ad,add,added,...,yes,yest,yesterday,yet,ym,yo,yoga,yogasana,yr,zed
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Inspect the variance of each column to identify the low-variance features

In [37]:
variances = X_df.var(axis=0)
print(variances.describe())

count    1079.000000
mean        0.000883
std         0.001011
min         0.000067
25%         0.000308
50%         0.000515
75%         0.001037
max         0.009344
dtype: float64

### Feature Selection:

Removes features (words) with low variance (below the threshold of 0.1), which are likely unimportant for classification.

In [38]:
# Convert TF-IDF sparse matrix to DataFrame for better analysis
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.001)
X_selected = selector.fit_transform(X_df)
X_df.shape[1], X_selected.shape[1]

(1079, 276)

In [44]:
# Get the original and selected feature names
original_features = set(X_df.columns)
selected_features = set(X_df.columns[selector.get_support()])

# Identify removed features
removed_features = original_features - selected_features

print(f"Number of features removed: {len(removed_features)}")
print("Removed features:")
print(removed_features)

Number of features removed: 803
Removed features:
{'store', 'stay', 'pussy', 'everything', 'answer', 'except', 'angry', 'beautiful', 'laugh', 'spoke', 'moan', 'player', 'flag', 'yar', 'ladies', 'remove', 'line', 'yoga', 'tuition', 'important', 'coz', 'match', 'din', 'wit', 'fighting', 'five', 'trust', 'role', 'charge', 'bath', 'hungry', 'walking', 'calling', 'fetch', 'leaves', 'works', 'process', 'announcement', 'keeping', 'rental', 'slow', 'smile', 'due', 'local', 'difficult', 'face', 'taking', 'brand', 'didnt', 'across', 'holding', 'wow', 'unable', 'sun', 'expensive', 'die', 'horny', 'amazing', 'surely', 'valued', 'fantastic', 'eve', 'rain', 'inviting', 'fantasy', 'study', 'totally', 'moon', 'date', 'mother', 'actually', 'wun', 'fix', 'mine', 'lonely', 'coffee', 'loving', 'pub', 'rather', 'plenty', 'original', 'complimentary', 'weed', 'matter', 'enter', 'convey', 'argument', 'station', 'currently', 'boss', 'booked', 'maid', 'horrible', 'rent', 'project', 'password', 'sol', 'arrange', 'behind', 'exam', 'til', 'learn', 'visit', 'wherever', 'network', 'ave', 'disturb', 'usual', 'dey', 'join', 'lose', 'onto', 'straight', 'bout', 'city', 'mum', 'spend', 'crazy', 'mad', 'yahoo', 'poly', 'wife', 'amount', 'boo', 'wa', 'airport', 'gay', 'doctor', 'easy', 'least', 'worth', 'fall', 'talking', 'contract', 'whatever', 'figure', 'eerie', 'funny', 'moment', 'pray', 'person', 'deal', 'music', 'double', 'handset', 'college', 'door', 'photo', 'hopefully', 'gas', 'seriously', 'otherwise', 'video', 'slave', 'south', 'saying', 'ge', 'entry', 'mon', 'al', 'system', 'caller', 'understand', 'friendship', 'bonus', 'read', 'rose', 'report', 'budget', 'salary', 'bother', 'partner', 'bank', 'fact', 'hostel', 'within', 'kiss', 'yan', 'murder', 'hand', 'content', 'national', 'tea', 'via', 'serious', 'swing', 'mode', 'confirm', 'able', 'valid', 'sec', 'honey', 'old', 'without', 'energy', 'lucky', 'pain', 'start', 'tried', 'body', 'semester', 'cut', 'wrong', 'self', 'stock', 'twice', 'father', 'sense', 'case', 'full', 'fast', 'ho', 'marry', 'towards', 'wonder', 'aha', 'book', 'ending', 'far', 'high', 'found', 'meant', 'doesnt', 'row', 'broke', 'finally', 'slowly', 'support', 'willing', 'zed', 'ten', 'pix', 'trouble', 'type', 'yest', 'pin', 'extra', 'yr', 'wine', 'yogasana', 'blood', 'somebody', 'forever', 'update', 'lady', 'worry', 'trip', 'hot', 'quality', 'run', 'small', 'ta', 'surprise', 'guide', 'hurt', 'minute', 'waking', 'return', 'crave', 'nobody', 'used', 'net', 'adult', 'collect', 'sea', 'air', 'pretty', 'top', 'daddy', 'jay', 'paper', 'street', 'choice', 'interesting', 'none', 'pic', 'side', 'marriage', 'completely', 'notice', 'strong', 'cake', 'cartoon', 'worse', 'beer', 'cancel', 'vote', 'search', 'anybody', 'daily', 'dint', 'sale', 'croydon', 'comes', 'telling', 'voucher', 'happening', 'holla', 'pizza', 'green', 'timing', 'yep', 'become', 'selection', 'receipt', 'ad', 'joke', 'move', 'club', 'apply', 'tear', 'ha', 'choose', 'cal', 'unlimited', 'whether', 'joy', 'outside', 'warm', 'especially', 'drug', 'ended', 'giving', 'cause', 'access', 'bill', 'murderer', 'price', 'revealed', 'colour', 'sound', 'romantic', 'winner', 'light', 'word', 'lovely', 'representative', 'rate', 'break', 'cabin', 'game', 'simple', 'round', 'training', 'write', 'dog', 'await', 'law', 'latest', 'secret', 'situation', 'smiling', 'listening', 'bitch', 'sister', 'knew', 'happiness', 'pete', 'vomit', 'summer', 'cum', 'ate', 'news', 'film', 'boy', 'cinema', 'lazy', 'normal', 'tour', 'lesson', 'site', 'believe', 'dating', 'ice', 'imagine', 'common', 'pass', 'wap', 'sen', 'singles', 'midnight', 'den', 'short', 'roommate', 'slept', 'wishing', 'lovable', 'lover', 'treat', 'worried', 'hospital', 'kept', 'member', 'decided', 'biz', 'second', 'men', 'delivery', 'obviously', 'ticket', 'pleasure', 'waste', 'loan', 'information', 'cine', 'complete', 'login', 'near', 'orchard', 'promise', 'add', 'sit', 'social', 'computer', 'spree', 'auction', 'dead', 'credit', 'draw', 'needs', 'bin', 'respond', 'recently', 'balance', 'rest', 'sending', 'mistake', 'cancer', 'travel', 'silent', 'must', 'quick', 'sexy', 'sis', 'inclusive', 'aft', 'belly', 'discount', 'flat', 'fat', 'sport', 'directly', 'lots', 'sex', 'model', 'wonderful', 'march', 'decide', 'accept', 'awake', 'posted', 'shirt', 'greet', 'living', 'ass', 'torch', 'sad', 'fixed', 'bedroom', 'deep', 'press', 'battery', 'land', 'saw', 'everyone', 'added', 'team', 'cheap', 'cover', 'fancy', 'ahead', 'po', 'goes', 'snow', 'activate', 'police', 'admirer', 'sometimes', 'mid', 'hold', 'digital', 'woke', 'area', 'mob', 'eating', 'advice', 'excellent', 'connection', 'gap', 'instead', 'song', 'water', 'code', 'la', 'sofa', 'mu', 'flirt', 'rite', 'sup', 'whats', 'wen', 'interested', 'unsold', 'subscription', 'together', 'sam', 'damn', 'heavy', 'touch', 'put', 'available', 'dream', 'present', 'whole', 'sunny', 'stupid', 'welcome', 'basically', 'egg', 'less', 'truth', 'hotel', 'menu', 'gee', 'laid', 'guy', 'card', 'cold', 'identifier', 'lift', 'reveal', 'spent', 'woman', 'though', 'apartment', 'appreciate', 'listen', 'open', 'family', 'gym', 'picked', 'cell', 'gave', 'correct', 'operator', 'gift', 'ugh', 'alone', 'barely', 'bag', 'forward', 'met', 'medical', 'rock', 'teasing', 'kind', 'orange', 'darling', 'hit', 'nights', 'cannot', 'buzz', 'quite', 'personal', 'away', 'tot', 'naked', 'standard', 'king', 'reason', 'country', 'user', 'moral', 'arrive', 'vary', 'landline', 'mood', 'busy', 'course', 'ago', 'kick', 'copy', 'amt', 'hop', 'somewhere', 'loyalty', 'official', 'review', 'feeling', 'group', 'tho', 'stylish', 'past', 'attempt', 'order', 'bold', 'luck', 'flower', 'un', 'inside', 'married', 'showing', 'sort', 'mo', 'almost', 'teach', 'random', 'future', 'jazz', 'request', 'advance', 'wear', 'holder', 'offer', 'exciting', 'polyphonic', 'safe', 'list', 'immediately', 'valentine', 'save', 'weather', 'blue', 'looking', 'fault', 'wid', 'na', 'em', 'naughty', 'log', 'statement', 'plus', 'party', 'usually', 'cute', 'searching', 'sub', 'reference', 'merry', 'shower', 'jordan', 'since', 'road', 'tonite', 'super', 'direct', 'weight', 'company', 'collection', 'remind', 'suite', 'boring', 'stopped', 'bye', 'catch', 'selected', 'sitting', 'competition', 'opinion', 'reaching', 'checked', 'ni', 'wake', 'running', 'question', 'couple', 'final', 'girl', 'scream', 'little', 'drop', 'camera', 'ride', 'closed', 'post', 'definitely', 'possible', 'style', 'meaning', 'single', 'tough', 'space', 'brilliant', 'afternoon', 'specially', 'paying', 'white', 'clean', 'current', 'campus', 'seeing', 'walk', 'library', 'else', 'relax', 'sign', 'lead', 'voice', 'age', 'everybody', 'starting', 'sell', 'bathe', 'eh', 'stand', 'ym', 'page', 'ignore', 'quiz', 'reward', 'miracle', 'drink', 'making', 'lost', 'quote', 'forget', 'transaction', 'opt', 'cup', 'hurry', 'felt', 'exactly', 'id', 'experience', 'ran', 'sick', 'gone', 'screaming', 'whenever', 'maximize', 'tired', 'wet', 'noon', 'nat', 'times', 'world', 'reading', 'pound', 'gal', 'character', 'link', 'point', 'till', 'smoke', 'turns', 'er', 'ar', 'begin', 'truly', 'hard', 'different', 'excuse', 'tat', 'following', 'sunshine', 'uncle', 'longer', 'supposed', 'mark', 'private', 'asleep', 'brother', 'earth', 'anyone', 'poor', 'norm', 'costa', 'seen', 'took', 'quit', 'either', 'power', 'season', 'simply', 'bought', 'childish', 'nature', 'share', 'idea', 'mate', 'red', 'park', 'wed', 'show', 'registered', 'black', 'track', 'however', 'glad', 'ex', 'opportunity', 'respect', 'discuss', 'sura', 'unless', 'award', 'train', 'informed', 'hell', 'click', 'weekly', 'wondering', 'sum'}

###  Stratified hold-out with 70:30 ratio

In [40]:
from sklearn.model_selection import train_test_split

# Sort the dataset by label to simulate a non-shuffled stratified split
df_sorted = df.sort_values(by='label_transform')

# Extract features and target
X = X_selected
y = df_sorted['label_transform']

# Perform a standard train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1234, stratify=None, shuffle=False
)

In [41]:

# Step 4: Report shapes of train and test matrices
print(f"Shape of train matrix: {X_train.shape}")
print(f"Shape of test matrix: {X_test.shape}")

Shape of train matrix: (3900, 276)
Shape of test matrix: (1672, 276)

In [42]:
# Step 5: Report the top 10 and bottom 10 rows of the training set
X_train_df = pd.DataFrame(X_train)
print("Top 10 rows of train set:")
print(X_train_df.head(10))

Top 10 rows of train set:
   0    1    2         3    4    5    6    7    8    9    ...  266  267  268  \
0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
1  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
2  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3  0.0  0.0  0.0  0.360677  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
4  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
5  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
6  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
7  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
8  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
9  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0

   269  270  271  272  273  274  275
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[10 rows x 276 columns]

In [43]:
print("\nBottom 10 rows of train set:")
print(X_train_df.tail(10))

Bottom 10 rows of train set:
      0    1    2    3    4    5    6    7    8    9    ...  266  267  268  \
3890  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3891  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3892  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3893  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3894  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3895  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3896  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3897  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3898  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
3899  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0

      269  270  271       272       273  274  275
3890  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0
3891  0.0  0.0  0.0  0.000000  0.394827  0.0  0.0
3892  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0
3893  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0
3894  0.0  0.0  0.0  0.687868  0.000000  0.0  0.0
3895  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0
3896  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0
3897  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0
3898  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0
3899  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0

[10 rows x 276 columns]